language: python
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: false
    python: '2.7'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.4'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.5'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: true
    python: '3.7'
  - os: linux
    dist: xenial
    sudo: true
    python: '3.8'
  - os: osx
    python: '2.7'
  - os: osx
    python: '3.4'
  - os: osx
    python: '3.5'
  - os: osx
    python: '3.6'
  - os: osx
    python: '3.7'
  - os: osx
    python: '3.8'
cache:
  directories:
    - ~/.cache/pip
install:
  - pip install numpy cython
  - python setup.py install
script:
  - python tests/test_jenks.py
addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy
