environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7.x"
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.4.x"
    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.5.x"
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.6.x"
    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.7.x"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "2.7.x"
    - PYTHON: "C:\\Python34-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.4.x"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.5.x"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6.x"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.7.x"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install wheel cython"

build_script:
  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python setup.py install"

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% python tests\\test_jenks.py"

after_test:
  - "%CMD_IN_ENV% python setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
